# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - type: tmpfs
        target: /dev/shm
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pgSQL
      POSTGRES_DB: nest-redis

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
