version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: db_seeding
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  cache:
    driver: local
